In [ ]:
# numpy exercises

In [3]:
#### 1. Import the numpy package under the name `np`

import numpy as np

In [4]:
#### 2. Create a null vector of size 10

a = np.zeros((10)) 
print(a, "\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 



In [28]:
#### 3. Create a null vector of size 10 but the fifth value which is 1

x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [30]:
#### 4. Create a vector with values ranging from 10 to 49

import numpy as np
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [44]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8

np.arange(0, 9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] 

import numpy as np

x = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(x)[0]

print(indices)


[0 1 4]


In [54]:
#### 7. Create a 3x3 identity matrix 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
#### 8. Create a 3x3x3 array with random values 

import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.93185098 0.92381495 0.11154123]
  [0.28141862 0.13389158 0.55542119]
  [0.50290219 0.32277395 0.0862373 ]]

 [[0.50919838 0.29864692 0.45171433]
  [0.38934928 0.97090091 0.94703258]
  [0.88450115 0.76732289 0.39547619]]

 [[0.50383838 0.69124959 0.01182852]
  [0.65308359 0.87164833 0.82585552]
  [0.94848912 0.86297362 0.65138476]]]


In [81]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values

import numpy as np
x = np.random.random((10,10))
print("10x10 numbers/array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

10x10 numbers/array:
[[0.41346541 0.20559446 0.2781147  0.36704229 0.2328751  0.86796456
  0.31483345 0.42329887 0.76417901 0.12892126]
 [0.95423914 0.96588458 0.44845023 0.28163421 0.62071928 0.37919974
  0.06882843 0.08593156 0.94474353 0.04982473]
 [0.8088443  0.34923586 0.85769378 0.2179621  0.39549262 0.15891873
  0.57950413 0.87467877 0.63455443 0.29285655]
 [0.08553397 0.86630542 0.37826147 0.42649433 0.23866087 0.00201418
  0.70433942 0.58195459 0.18207479 0.30074913]
 [0.5024387  0.48572275 0.3013802  0.35449121 0.10423119 0.51234693
  0.6292638  0.32781655 0.41812119 0.97721739]
 [0.71021342 0.74516216 0.17360132 0.49429517 0.86109504 0.33782352
  0.49281054 0.22151487 0.83597659 0.35960785]
 [0.25945066 0.25832832 0.59976338 0.19424794 0.66696325 0.97802394
  0.0321249  0.98993324 0.62584055 0.2296986 ]
 [0.77280558 0.96419241 0.14701747 0.6674397  0.07608017 0.36293402
  0.29467401 0.73530986 0.19868134 0.42776649]
 [0.45499759 0.24357312 0.50772677 0.59162095 0.78528192 0.

In [83]:
#### 10. Create a random vector of size 30 and find the mean value

import numpy as np
x = np.random.random(30)
print("30 numbers:")
print(x)

Z = np.random.random(30)
m = Z.mean()
print("mean value:")
print(m)

30 numbers:
[0.10048684 0.0265845  0.63424023 0.88511964 0.29487705 0.72299156
 0.81969051 0.30274723 0.66434396 0.98608016 0.87828766 0.97062346
 0.84109988 0.07484956 0.04671109 0.77060836 0.1570456  0.42171444
 0.1604621  0.06171925 0.80835636 0.93072846 0.33952112 0.12746586
 0.6367213  0.41776824 0.06841966 0.15194441 0.22759973 0.20414792]
mean value:
0.44848618938009394


In [86]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [91]:
#### 12. Normalize a 5x5 random matrix DUDA

import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.0099487  0.59432248 0.46437488]
 [0.84512058 0.20107841 0.27643746]
 [0.05889685 0.5934969  0.33986173]]
After normalization:
[[0.         0.69970481 0.54411097]
 [1.         0.22885075 0.31908253]
 [0.05860848 0.69871629 0.39502411]]


In [89]:
#### 13. How to find common values between two arrays?

import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [94]:
#### 14. Create a random vector of size 10 and sort it

import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)


Original array:
[0.79282807 0.48461656 0.44612373 0.51762386 0.82730278 0.80794781
 0.9705311  0.08059736 0.9278478  0.55273602]
Sorted array:
[0.08059736 0.44612373 0.48461656 0.51762386 0.55273602 0.79282807
 0.80794781 0.82730278 0.9278478  0.9705311 ]


In [102]:
#### 15. Create random vector of size 10 and replace the maximum value by 0

import numpy as np
x = np.random.random(10)
print("\n" "Original array:" "\n")
print(x)
x[x.argmax()] = 0 
print("\n" "Maximum value replaced by 0:" "\n")
print(x)



Original array:

[0.83127602 0.09871824 0.65391037 0.28640524 0.88929149 0.23669208
 0.88858086 0.43731679 0.23605378 0.34693646]

Maximum value replaced by 0:

[0.83127602 0.09871824 0.65391037 0.28640524 0.         0.23669208
 0.88858086 0.43731679 0.23605378 0.34693646]


In [108]:
#### 16. Subtract the mean of each row of a matrix

import numpy as np
print("Original matrix:\n")
X = np.random.rand(1, 5)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.2669491  0.70167233 0.81354661 0.09133496 0.46384827]]

Subtract the mean of each row of the said matrix:

[[-0.20052116  0.23420208  0.34607636 -0.3761353  -0.00362199]]


In [109]:
#### 17. How to get the n largest values of an array

import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

